"""Initial schema

Revision ID: 021685bc124f
Revises: 
Create Date: 2019-09-30 21:40:56.219194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021685bc124f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
